name: graphmap
owner: bgruening
categories:
  - Assembly
description: Mapper for long, error-prone reads.
homepage_url: https://github.com/fenderglass/Flyeisovic/graphmap/
long_description: |
  GraphMap is a novel mapper targeted at aligning long, error-prone third-generation sequencing data.
It is designed to handle Oxford Nanopore MinION 1d and 2d reads with very high sensitivity and accuracy, and also presents a significant improvement over the state-of-the-art for PacBio read mappers.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/graphmap
type: unrestricted
